/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package andromaly.main;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int clear_text_button=0x7f060003;
        public static final int edit_text=0x7f060002;
        public static final int linear_layout=0x7f060001;
        public static final int scroll_view=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int notepad_list=0x7f030001;
    }
    public static final class raw {
        public static final int config_features=0x7f040000;
        public static final int configurations=0x7f040001;
        public static final int local_server=0x7f040002;
        public static final int notes_row=0x7f040003;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int clear_text=0x7f050003;
        public static final int hello=0x7f050000;
        public static final int menu_reset=0x7f050006;
        public static final int menu_stop=0x7f050005;
        public static final int menu_write_profile=0x7f050007;
        public static final int restartAgent=0x7f050004;
        public static final int welcome=0x7f050002;
    }
}
